import type { Metadata } from "next";
import { LegalPage, Section } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Terms of Service — ClarityAI",
  description:
    "The terms for using ClarityAI: what it is, what it is not, and the limits of relying on AI-generated explanations.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="June 19, 2026">
      <p>
        Welcome, and thank you for using ClarityAI. These terms are a plain-language agreement
        between you and ClarityAI about how the service may be used. We have kept the legalese to a
        minimum, because a tool about clarity should be clear about itself. By using ClarityAI, you
        agree to what follows.
      </p>

      <Section heading="What ClarityAI is">
        <p>
          ClarityAI takes a confusing document — a letter, bill, notice, or form — and turns it into
          a plain-language summary, an action checklist, and pointers to local help. You can also
          ask follow-up questions in the chat. It is a comprehension aid: a way to understand what
          something means and what your options are.
        </p>
      </Section>

      <Section heading="What ClarityAI is not">
        <p>
          ClarityAI is <strong>not a lawyer, doctor, accountant, or caseworker</strong>, and its
          output is <strong>not legal, medical, or financial advice</strong>. It is generated by AI,
          which can be confident and still be wrong. It may misread a date, miss a clause, or
          simplify away an important nuance.
        </p>
        <ul>
          <li>Always verify dates, amounts, and deadlines against the original document.</li>
          <li>For decisions with real consequences, consult a qualified professional.</li>
          <li>ClarityAI never files, signs, submits, or sends anything on your behalf — you remain in control of every action.</li>
        </ul>
      </Section>

      <Section heading="Using the service responsibly">
        <p>By using ClarityAI, you agree that you will not:</p>
        <ul>
          <li>Use it for anything unlawful, or to attempt to harm, defraud, or deceive others.</li>
          <li>Upload content you do not have the right to share.</li>
          <li>Try to overwhelm, probe, scrape, or disrupt the service or its providers.</li>
          <li>Rely on it as your sole basis for a legal, medical, financial, or safety decision.</li>
        </ul>
      </Section>

      <Section heading="Accuracy and availability">
        <p>
          We work to make ClarityAI helpful, but we cannot guarantee that every explanation is
          accurate, complete, or current, nor that the service will always be available. The tool
          depends on third-party AI and search providers and may change, pause, or break without
          notice. It is provided <strong>&ldquo;as is&rdquo;</strong>, without warranties of any
          kind.
        </p>
      </Section>

      <Section heading="Limitation of liability">
        <p>
          To the fullest extent permitted by law, ClarityAI and its makers are not liable for any
          loss or harm arising from your use of, or reliance on, the service or its output. You use
          ClarityAI as one input among many — the final judgment, and responsibility for acting on
          it, is yours.
        </p>
      </Section>

      <Section heading="Privacy">
        <p>
          Your privacy is covered separately and in detail in our{" "}
          <a href="/privacy">Privacy Policy</a>. In short: no accounts, no database, processing in
          memory, and on-device storage you can erase at any time.
        </p>
      </Section>

      <Section heading="Changes to these terms">
        <p>
          We may update these terms as the service evolves. When we do, we will revise the date at
          the top of this page. Continuing to use ClarityAI after a change means you accept the
          updated terms.
        </p>
      </Section>

      <Section heading="In one sentence">
        <p>
          ClarityAI helps you understand and organize — please treat it as a knowledgeable friend
          explaining the gist, not as the final word, and verify anything that truly matters.
        </p>
      </Section>
    </LegalPage>
  );
}
